Repository codesquad-masters2024-team07/issue-tracker, pull requests merged in 2024-05, with the labels that each got.

#4 [BE] 엔티티 클래스 작성
  build.gradle
  src/main/java/codesquad/issuetracker/comment/Comment.java
  src/main/java/codesquad/issuetracker/issue/Issue.java
  src/main/java/codesquad/issuetracker/label/Label.java
  src/main/java/codesquad/issuetracker/milestone/Milestone.java
  src/main/java/codesquad/issuetracker/user/User.java
Labels: BE

#5 [BE] 열린 이슈, 닫힌 이슈 조회 기능 구현 #3
  src/main/java/codesquad/issuetracker/issue/Issue.java
  src/main/java/codesquad/issuetracker/issue/IssueController.java
  src/main/java/codesquad/issuetracker/issue/IssueRepository.java
  src/main/java/codesquad/issuetracker/issue/IssueService.java
  src/main/java/codesquad/issuetracker/issue/LabelRef.java
  src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
  src/test/java/codesquad/issuetracker/issue/IssueRepositoryTest.java
Labels: BE

#6 [BE] 마일스톤과 라벨의 목록을 전부 불러오는 기능 구현
  src/main/java/codesquad/issuetracker/label/Label.java
  src/main/java/codesquad/issuetracker/label/LabelController.java
  src/main/java/codesquad/issuetracker/label/LabelRepository.java
  src/main/java/codesquad/issuetracker/label/LabelService.java
  src/main/java/codesquad/issuetracker/milestone/Milestone.java
  src/main/java/codesquad/issuetracker/milestone/MilestoneController.java
  src/main/java/codesquad/issuetracker/milestone/MilestoneRepository.java
  src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
  src/test/java/codesquad/issuetracker/IssueTrackerApplicationTests.java
  src/test/java/codesquad/issuetracker/label/LabelControllerTest.java
  src/test/java/codesquad/issuetracker/label/LabelRepositoryTest.java
  src/test/java/codesquad/issuetracker/label/LabelServiceTest.java
  src/test/java/codesquad/issuetracker/milestone/MilestoneControllerTest.java
  src/test/java/codesquad/issuetracker/milestone/MilestoneRepositoryTest.java
  src/test/java/codesquad/issuetracker/milestone/MilestoneServiceTest.java
Labels: enhancement, BE

#9 [BE] Github actions와 도커를 이용한 CI/CD 구현
  .github/workflows/dev.yaml
  BE/issue-tracker/Dockerfile
  BE/issue-tracker/README.md
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/Milestone.java
  BE/issue-tracker/src/main/resources/sql/schema/schema.sql
  README.md
Labels: BE, deploy

#10 ♻️ refactor: 마일스톤 페이지 리펙토링
  fe/src/App.tsx
  fe/src/Providers/ModifyDeleteProvider.tsx
  fe/src/app/MilestonesPage/page.tsx
  fe/src/components/MilestoneContainer/MilestoneCard.tsx
  fe/src/components/MilestoneContainer/MilestoneFeed.tsx
  fe/src/components/MilestoneContainer/ModifyDeleteUI.tsx
  fe/src/components/MilestoneContainer/Nav.tsx
  fe/src/pages/IssueProduct.tsx
  fe/src/pages/IssuesPage.tsx
  fe/src/pages/LabelsPage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/MilestonesPage.tsx
  fe/src/pages/NewPage.tsx
Labels: FE

#11 ✨ chore: 마일스톤, 레이블 생성 및 수정 기능 추가
  fe/db.json
  fe/src/Providers/ModifyDeleteProvider.tsx
  fe/src/components/IssueContainer/FeedNav.tsx
  fe/src/components/IssueContainer/IssueCard.tsx
  fe/src/components/IssueContainer/IssueFeed.tsx
  fe/src/components/IssueContainer/Nav.tsx
  fe/src/components/LabelsMilestones/Labels/LabelCard.tsx
  fe/src/components/LabelsMilestones/Labels/LabelEditUI.tsx
  fe/src/components/LabelsMilestones/Labels/LabelFeed.tsx
  fe/src/components/LabelsMilestones/Milestones/MilestoneCard.tsx
  fe/src/components/LabelsMilestones/Milestones/MilestoneEditUI.tsx
  fe/src/components/LabelsMilestones/Milestones/MilestoneFeed.tsx
  fe/src/components/LabelsMilestones/Nav.tsx
  fe/src/components/MilestoneContainer/FeedNav.tsx
  fe/src/components/MilestoneContainer/MilestoneFeed.tsx
  fe/src/index.css
  fe/src/pages/LabelsPage.tsx
  fe/src/pages/MilestonesPage.tsx
  fe/src/util/FilterUI.tsx
Labels: FE

#15 [BE] 이슈 관련 기능 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/Comment.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ResourceNotFoundException.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Assignee.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueAttachedLabel.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/LabelRef.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/User.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserResponse.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueRepositoryTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/user/UserRepositoryTest.java
Labels: enhancement, BE

#16 [BE] 마일스톤 및 이슈의 순환 의존성 문제 해결
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/resources/sql/schema/schema.sql
Labels: bug

#17 [BE] 이슈 Soft Delete 기능 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueRepositoryTest.java
Labels: enhancement, BE

#18 ✨ feat: 이슈 생성 페이지 구현
  fe/src/common/APIUtils.ts
  fe/src/common/FilterUI.tsx
  fe/src/common/NotFound.tsx
  fe/src/common/Sidebar.tsx
  fe/src/common/Uploader.tsx
  fe/src/common/UtilUI.tsx
  fe/src/components/IssueContainer/FeedNav.tsx
  fe/src/components/IssueContainer/IssueFeed.tsx
  fe/src/components/IssueContainer/Nav.tsx
  fe/src/components/LabelsMilestones/Labels/LabelFeed.tsx
  fe/src/components/LabelsMilestones/Milestones/MilestoneFeed.tsx
  fe/src/components/LabelsMilestones/Nav.tsx
  fe/src/components/NewIssue/Comment.tsx
  fe/src/index.css
  fe/src/pages/IssuesPage.tsx
  fe/src/pages/LabelsPage.tsx
  fe/src/pages/MilestonesPage.tsx
  fe/src/pages/NewPage.tsx
Labels: FE

#19 [BE] 전역 예외 핸들러 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ErrorCode.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/GlobalExceptionHandler.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ResourceNotFoundException.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
Labels: enhancement, BE

#23 [BE] 라벨 목록 페이지 구현
  .github/ISSUE_TEMPLATE/기능-추가-이슈.md
  .github/ISSUE_TEMPLATE/버그-이슈.md
  BE/issue-tracker/build.gradle
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/Label.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/TextColor.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/Milestone.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneCustom.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
  BE/issue-tracker/src/main/resources/sql/schema/schema.sql
  BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelControllerTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelRepositoryTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelServiceTest.java
Labels: enhancement, BE

#27 [BE] 이슈 리팩토링
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/Comment.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
  BE/issue-tracker/src/main/resources/sql/schema/schema.sql
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueRepositoryTest.java
Labels: BE

#28 [BE] 라벨 CRUD기능 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/aop/HttpAspect.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepositoryImpl.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/utils/FieldnameConverter.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelControllerTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelRepositoryTest.java
Labels: enhancement, BE

#29 [BE] 삭제된 라벨이 불러와진 문제 해결
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepositoryImpl.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/label/LabelServiceTest.java
Labels: bug, BE

#30 [BE] 이슈 상세 페이지에 마일스톤 정보 추가
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/DetailIssueResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/SimpleMilestoneResponse.java
Labels: enhancement, BE

#33 [BE] 라벨 및 마일스톤 리팩터링
  BE/issue-tracker/src/main/java/codesquad/issuetracker/count/dto/IssueCount.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/count/dto/LabelMilestoneCount.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/count/service/CountService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/global/repository/CrudRepositoryCustom.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/global/repository/CrudRepositoryCustomImpl.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelCustomRepositoryImpl.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/LabelService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelListResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/LabelResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/Milestone.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneCustom.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneCustomRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepositoryCustom.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepositoryCustomImpl.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneListResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
Labels: BE, refactor

#35 [BE] 마일스톤 due date의 타입 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
Labels: bug, BE

#36 [BE] 로그인, 회원가입 기능 구현
  BE/issue-tracker/build.gradle
  BE/issue-tracker/src/main/java/codesquad/issuetracker/config/WebConfig.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ErrorCode.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/GlobalExceptionHandler.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/PasswordMismatch.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/TokenExpiredException.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/UserAlreadyExist.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/UserNotFoundException.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/User.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/auth/AuthInterceptor.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/auth/JwtTokenProvider.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/LoginResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserLoginRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserResponse.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/user/UserControllerTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/user/UserRepositoryTest.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/user/UserServiceTest.java
Labels: enhancement, BE

#37 [BE] 사용자 프로필 사진 저장 기능 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/User.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/UserService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/LoginResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/SimpleUserResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/UserResponse.java
  BE/issue-tracker/src/main/resources/sql/schema/schema.sql
Labels: enhancement, BE

#38 [BE] Issue 생성 시 milestoneId가 null인 경우 처리
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
Labels: enhancement, BE

#43 [BE]
  BE/issue-tracker/build.gradle
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/GoogleOAuthService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/ProfileMapper.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/config/WebConfig.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ErrorCode.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/GlobalExceptionHandler.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/UnauthorizedException.java
Labels: enhancement, BE

#44 [BE] 이슈 목록 응답 데이터 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/label/dto/SimpleLabelResponse.java
Labels: bug, BE

#45 [BE] OAuth 리다이렉트 버그 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/ErrorCode.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/exception/GlobalExceptionHandler.java
Labels: bug, BE

#48 [BE] 댓글 내용 수정 기능 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/Comment.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentResponse.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/comment/CommentUpdateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
Labels: enhancement, BE

#49 [BE] 이슈 상세 페이지를 불러오지 못하는 문제 해결
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
Labels: bug, BE

#50 [BE] OAuth 로그인 기능 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/auth/JwtTokenProvider.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/user/dto/SimpleUserResponse.java
Labels: enhancement, BE

#51 [BE] OAuth 버그 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
  BE/issue-tracker/src/test/java/codesquad/issuetracker/issue/IssueControllerTest.java
Labels: bug, BE

#53 [BE] 이슈의 담당자, 레이블, 마일스톤을 추가/제거하는 기능 구현
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/AssigneeUpdateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/AttachedLabelUpdateRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/MilestoneUpdateRequest.java
Labels: enhancement, BE

#54 [BE] 이슈 제목이 업데이트 되지 않는 오류
  BE/issue-tracker/src/main/java/codesquad/issuetracker/global/repository/CrudRepositoryCustomImpl.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
Labels: bug, BE

#55 [BE] 이슈 생성이 안되는 오류 해결
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/dto/IssueCreateRequest.java
Labels: bug, BE

#56 [BE]마일스톤 반환타입이 오류 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/Milestone.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepositoryCustomImpl.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneRequest.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/dto/MilestoneResponse.java
Labels: bug, BE

#58 [BE] 마일스톤이 null일 때 발생하는 오류 해결
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/Issue.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/issue/IssueService.java
Labels: bug, BE

#59 [BE] 마일스톤 상태를 변경시키는 API 수정
  BE/issue-tracker/src/main/java/codesquad/issuetracker/OAuth/OAuthController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneController.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneRepository.java
  BE/issue-tracker/src/main/java/codesquad/issuetracker/milestone/MilestoneService.java
Labels: enhancement, BE
